=== bhagyamoharana/SOA-LAB2/laptop.dtd
<!ELEMENT laptop (manufacturer, model,memory, disk, screen, accessories+)>
<!ELEMENT  manufacturer (#PCDATA)> <!--text-->
<!ELEMENT  model (#PCDATA)>
<!ELEMENT  memory (#PCDATA)>
<!ELEMENT  disk (#PCDATA)>
<!ELEMENT  screen (#PCDATA)>
<!ELEMENT  accessories (#PCDATA)>

<!ATTLIST manufacturer
              country (Poland|Ireland) #REQUIRED
              continent CDATA #REQUIRED>

=== bhagyamoharana/SOA-LAB2/laptop.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE laptop SYSTEM "laptop.dtd">


<laptop>
    <manufacturer country= "Poland"  continent = "Europe">Dell</manufacturer>
    <model>Inspiron</model>
    <memory>512M</memory>
    <disk>60G</disk>
    <screen>15 inch</screen>
    <accessories>Bag</accessories>
    <accessories>Mouse</accessories>
    
</laptop>
