=== bhagyamoharana/SOA-LAB2/student.dtd
<!ELEMENT student (idnumber, college, course, year, subjects )>
<!ELEMENT  idnumber (#PCDATA)> <!--text-->
<!ELEMENT  college (#PCDATA)> <!--text-->
<!ELEMENT  dob (#PCDATA)>
<!ELEMENT  course (#PCDATA)>
<!ELEMENT  subjects (subject+)>  <!--children-->
<!ELEMENT  subject (#PCDATA)>
<!ELEMENT  year EMPTY>    <!--without brackets-->
<!ATTLIST college shortname CDATA #FIXED "AIT"> <!--fixed is another way of saying required-->
<!ATTLIST year value (1|2|3|4|5) #IMPLIED>

<!--#IMPLIED IS used if you dont want to force the xml author to include an attribute but dont have a default value either-->

=== bhagyamoharana/SOA-LAB2/student.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE student SYSTEM "student.dtd">



<student>
    <idnumber>A00258759</idnumber>
    <college shortname = "AIT">Athlone Institue of Technology</college>
    
    <course>MSC In Software Engg</course>
    <year value = "5" />
   
    <subjects>
        <subject>SOA</subject>
        <subject>Telecoms</subject>
        <subject>SW Development</subject>
    </subjects>
    
    
    
</student>
